### ISSUE TITLE
Ошибка совместимости с FakeXrmEasy

### ISSUE THREAD

**Issue by KAV-91** [FixRM/D365Extensions#15]
Пример QueryExpression:
```
var query = new QueryExpression(Account.EntityLogicalName)
        {
            ColumnSet = new ColumnSet<Account>(c => c.AccountId),
            LinkEntities =
            {
                new LinkEntity<Account, PhoneCall>(
                    a => a.AccountId,
                    p => p.RegardingObjectId,
                    JoinOperator.Inner)
                {
                    LinkCriteria =
                    {
                        Conditions =
                        {
                            new ConditionExpression<PhoneCall>(p => p.Description, ConditionOperator.Equal, "Test")
                        }
                    }
                }
            }
        };
```
FakeXrmEasy падает с ошибкой "Attribute phonecall1.description not found for type ..."
Проблема в том, что ConditionExpression безусловно задает поле EntityName, а FakeXrmEasy считает его приоритетным и ищет в запросе Link с соответствующим алиасом. 
Версия D365Extensions 1.5.3
Версия FakeXrmEasy 2.3.1

**Comment by FixRM** [comment]
Исправлено в [v2.2.0](https://github.com/FixRM/D365Extensions/releases/tag/v2.2.0)

**Comment by KAV-91** [comment]
Если переписать пример выше не используя Object initializer ошибка также воспроизводится

```
 var query = new QueryExpression(Account.EntityLogicalName)
            {
                ColumnSet = new ColumnSet<Account>(c => c.AccountId)
            };
            LinkEntity<Account, PhoneCall> item = new LinkEntity<Account, PhoneCall>(
                a => a.AccountId,
                p => p.RegardingObjectId,
                JoinOperator.Inner);
            item.LinkCriteria.AddCondition<PhoneCall>(p => p.Description, ConditionOperator.Equal, "Test");
            query.LinkEntities.Add(item);
 ```

Ошибка в методе-расширении Microsoft.Xrm.Sdk.Query.FilterExpressionExtensions.AddCondition<T>

**Comment by FixRM** [comment]
> Если переписать пример выше не используя Object initializer ошибка также воспроизводится
> 
> ```
>  var query = new QueryExpression(Account.EntityLogicalName)
>             {
>                 ColumnSet = new ColumnSet<Account>(c => c.AccountId)
>             };
>             LinkEntity<Account, PhoneCall> item = new LinkEntity<Account, PhoneCall>(
>                 a => a.AccountId,
>                 p => p.RegardingObjectId,
>                 JoinOperator.Inner);
>             item.LinkCriteria.AddCondition<PhoneCall>(p => p.Description, ConditionOperator.Equal, "Test");
>             query.LinkEntities.Add(item);
> ```
> 
> Ошибка в методе-расширении Microsoft.Xrm.Sdk.Query.FilterExpressionExtensions.AddCondition

Fixed in [v2.7.1](https://github.com/FixRM/D365Extensions/releases/tag/v2.7.1)
