### ISSUE TITLE
NullReferenceException при задании ColumnSet<T> == null

### ISSUE THREAD

**Issue by KAV-91** [FixRM/D365Extensions#16]
Пример метода:
```
public T TryGetById<T> (Guid id, ColumnSet<T> columns = null) where T: Entity
{
   var query = new QueryExpression(new T().LogicalName)
      {
...
          ColumnSet = columns
...
      };
return OrganizationService.RetriveMultiple(query).Entities.FirstOrDefault()?.ToEntity<T>();
}
```
При вызове TryGetById(Guid.Parse("dc82564f-246a-4eee-b461-be84adf74430")) упадет с ошибкой

**Comment by FixRM** [comment]
Привет @KAV-91. Не увидел подобных вызовов в моей библиотеке, подскажите где они, если они там есть. Что касается вашего кода, попробуйте поменять его на
```C#
public T TryGetById<T> (Guid id, ColumnSet<T> columns = new ColumnSet<T>()) where T: Entity
```

**Comment by FixRM** [comment]
Исправлено в [v2.2.0](https://github.com/FixRM/D365Extensions/releases/tag/v2.2.0)
