### ISSUE TITLE
Невозможно напрямую задать атрибут Id в ColumnSet<T> или ConditionExpression<T>

### ISSUE THREAD

**Issue by KAV-91** [FixRM/D365Extensions#17]
```
var query = new QueryExpression(Account.EntityLogicalName)
        {
            //...
            ColumnSet = new ColumnSet<Account>(a => a.Id) 
            //...
        };

```
a.Id это должно развернуться в accountid так как у Id есть атрибут [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")].
Не работает из-за переопределения (override) этого свойства, а метод D365Extensions.LogicalName.GetName<T> получает member именно от базовой Entity

**Comment by FixRM** [comment]
Привет @KAV-91. Не знал про такое поведение, спасибо. Вижу что `ParameterExpression` в лямбда выражении связан с типом `Account` но `UnaryExpression` в его теле ссылается на `MemberInfo` в `Entity`. Вероятно, потому что это его "declaring type".  Не знаю, можно ли это как-то поправить...

 Почему нужен именно Id? Вы всегда можете использовать `a=> a.AccountId`.

**Comment by FixRM** [comment]
Исправлено в [v2.2.0](https://github.com/FixRM/D365Extensions/releases/tag/v2.2.0)
